# Generated by Django 6.0.6 on 2026-06-19 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='comment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
