# Generated by Django 6.0.6 on 2026-06-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
