# Generated by Django 6.0.6 on 2026-06-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_alter_dish_options_dish_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
